const { contextBridge, ipcRenderer, webUtils } = require('electron');

const invoke = (ch) => (...args) => ipcRenderer.invoke(ch, ...args);

contextBridge.exposeInMainWorld('cinema', {
  getLibrary: invoke('lib:get'),
  scan: invoke('lib:scan'),
  pickRoots: invoke('roots:pick'),
  addRoots: invoke('roots:add'),
  removeRoot: invoke('roots:remove'),
  setMeta: invoke('meta:set'),
  pickImage: invoke('image:pick'),
  resetImage: invoke('image:reset'),
  coverFromFrame: invoke('image:fromThumb'),
  setProgress: invoke('progress:set'),
  setSettings: invoke('settings:set'),
  saveThumb: invoke('thumb:save'),
  clearThumbs: invoke('thumbs:clear'),
  readSub: invoke('sub:read'),
  pickSub: invoke('sub:pick'),
  showInFolder: invoke('shell:show'),
  openDir: invoke('shell:openDir'),
  openPotPlayer: invoke('potplayer:open'),
  pickPotPlayer: invoke('potplayer:pick'),
  saveScreenshot: invoke('screenshot:save'),
  setFullscreen: invoke('win:fullscreen'),
  setAlwaysOnTop: invoke('win:alwaysOnTop'),
  clearRoots: invoke('roots:clear'),
  factoryReset: invoke('app:factoryReset'),
  rootsInfo: invoke('roots:info'),
  openWeb: invoke('shell:openWeb'),
  webSearch: invoke('web:search'),
  webApply: invoke('web:apply'),
  webClear: invoke('web:clear'),
  renameSeries: invoke('series:rename'),
  setSplit: invoke('series:setSplit'),
  mediaProbe: invoke('media:probe'),
  mediaStream: invoke('media:stream'),
  mediaStop: invoke('media:stop'),
  mediaSub: invoke('media:sub'),
  mediaThumb: invoke('media:thumb'),
  mediaAvailable: invoke('media:available'),
  appInfo: invoke('app:info'),
  playersDetect: invoke('players:detect'),
  playersOpen: invoke('players:open'),
  playersPick: invoke('players:pick'),
  openDataDir: invoke('app:openDataDir'),
  webClearAll: invoke('web:clearAll'),
  webFetchAll: invoke('web:fetchAll'),
  webCancel: invoke('web:cancel'),
  onWebProgress: (cb) => ipcRenderer.on('web:progress', (e, d) => cb(d)),
  pathForFile:(file) => { try { return webUtils.getPathForFile(file); } catch (e) { return ''; } },
  onLibChanged: (cb) => ipcRenderer.on('lib:changed', () => cb()),
  onFullscreen: (cb) => ipcRenderer.on('win:fullscreen', (e, v) => cb(v)),
});
